In [11]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [12]:
project_root = '/mnt/data/sajadeb/Gen_LTR'

X_real_cal = np.load(os.path.join(project_root, 'data', 'california', 'X_num_train.npy'))
X_real_letor = np.load(os.path.join(project_root, 'data', 'MQ2007', 'npy', 'Fold1', 'X_num_train.npy'))
X_real_mslr = np.load(os.path.join(project_root, 'data', 'MSLR-WEB30K', 'npy', 'Fold1', 'X_num_train.npy'))

n_features_cal = X_real_cal.shape[1]
n_features_letor = X_real_letor.shape[1]
n_features_mslr = X_real_mslr.shape[1]

In [13]:
def calculate_statistics(X_real, n_features):
    stats_dict = {
        'Mean': np.mean(X_real, axis=0),
        'Std': np.std(X_real, axis=0),
        'Min': np.min(X_real, axis=0),
        'Max': np.max(X_real, axis=0),
        'Skewness': stats.skew(X_real, axis=0),
        'Kurtosis': stats.kurtosis(X_real, axis=0),
        'Unique Values': [len(np.unique(X_real[:, i])) for i in range(n_features)]
    }
    stats_df = pd.DataFrame(stats_dict, index=[f'Feature {i}' for i in range(n_features)])
    return stats_df

In [14]:
calculate_statistics(X_real_cal, n_features_cal)

,Mean,Std,Min,Max,Skewness,Kurtosis,Unique Values
Feature 0,3.883188,1.907002,0.499900,15.000100,1.633187,4.925376,9185
Feature 1,28.601332,12.614959,1.000000,52.000000,0.059778,-0.796241,52
Feature 2,5.425831,2.029238,0.846154,59.875000,8.713568,153.071152,12648
Feature 3,1.093547,0.366874,0.333333,15.312500,16.396753,399.601959,10021
Feature 4,1417.431763,1145.426147,3.000000,35682.000000,5.663954,97.792084,3378
Feature 5,3.049111,7.186295,0.750000,599.714294,71.329308,5437.933105,12369
Feature 6,35.633018,2.142821,32.540001,41.950001,0.473810,-1.100981,831
Feature 7,-119.566299,2.005063,-124.349998,-114.309998,-0.299193,-1.325005,795

In [15]:
calculate_statistics(X_real_letor, n_features_letor)

,Mean,Std,Min,Max,Skewness,Kurtosis,Unique Values
Feature 0,0.163040,0.236597,0.0,1.0,2.167572,4.174278,21877
Feature 1,0.137577,0.249487,0.0,1.0,2.125872,3.960963,349
Feature 2,0.252003,0.341057,0.0,1.0,1.049008,-0.257308,86
Feature 3,0.142365,0.308507,0.0,1.0,2.024891,2.637230,22
Feature 4,0.166726,0.236584,0.0,1.0,2.145161,4.074288,22492
Feature 5,0.000000,0.000000,0.0,0.0,NaN,NaN,1
Feature 6,0.000000,0.000000,0.0,0.0,NaN,NaN,1
Feature 7,0.000000,0.000000,0.0,0.0,NaN,NaN,1
Feature 8,0.000000,0.000000,0.0,0.0,NaN,NaN,1
Feature 9,0.000000,0.000000,0.0,0.0,NaN,NaN,1
Feature 10,0.235068,0.282392,0.0,1.0,1.387279,0.795667,31245
Feature 11,0.137391,0.248091,0.0,1.0,2.090102,3.768083,5103
Feature 12,0.254223,0.341739,0.0,1.0,0.986910,-0.455300,4051
Feature 13,0.131329,0.292763,0.0,1.0,2.143322,3.194999,1363
Feature 14,0.241541,0.283170,0.0,1.0,1.354329,0.691562,32170
Feature 15,0.143784,0.237826,0.0,1.0,2.363477,4.949755,31967
Feature 16,0.194316,0.237848,0.0,1.0,1.774966,2.792047,2020
Feature 17,0.279862,0.273250,0.0,1.0,0.947514,0.180820,828
Feature 18,0.405705,0.254396,0.0,1.0,0.594111,-0.269509,426
Feature 19,0.144223,0.237765,0.0,1.0,2.361687,4.942666,33064
Feature 20,0.628539,0.270277,0.0,1.0,-0.711294,-0.350583,36015
Feature 21,0.569690,0.272692,0.0,1.0,-0.478123,-0.642541,35842
Feature 22,0.561499,0.288323,0.0,1.0,-0.399290,-0.899136,35603
Feature 23,0.551766,0.280865,0.0,1.0,-0.377697,-0.839958,35627
Feature 24,0.206532,0.312508,0.0,1.0,1.252364,0.198758,8753
Feature 25,0.187870,0.315822,0.0,1.0,1.449722,0.595638,10114
Feature 26,0.160991,0.294533,0.0,1.0,1.672277,1.432321,9806
Feature 27,0.176746,0.311838,0.0,1.0,1.584504,1.003533,9493
Feature 28,0.253796,0.333184,0.0,1.0,0.907651,-0.635335,8088
Feature 29,0.225085,0.339090,0.0,1.0,1.172878,-0.211260,9747
Feature 30,0.221416,0.357252,0.0,1.0,1.246309,-0.125516,9284
Feature 31,0.215370,0.336505,0.0,1.0,1.270914,0.032276,9408
Feature 32,0.135765,0.293282,0.0,1.0,1.974117,2.373350,3119
Feature 33,0.080453,0.236137,0.0,1.0,3.065103,8.111772,3396
Feature 34,0.081254,0.249663,0.0,1.0,3.022390,7.612105,2931
Feature 35,0.077596,0.235945,0.0,1.0,3.157152,8.625953,3041
Feature 36,0.632327,0.268641,0.0,1.0,-0.720047,-0.329133,37486
Feature 37,0.569308,0.271122,0.0,1.0,-0.464327,-0.657195,37480
Feature 38,0.565276,0.284642,0.0,1.0,-0.406802,-0.866607,37157
Feature 39,0.554954,0.281057,0.0,1.0,-0.377247,-0.860636,37149
Feature 40,0.079600,0.200222,0.0,1.0,3.490499,11.937680,21004
Feature 41,0.101546,0.206179,0.0,1.0,3.161332,9.862607,3608
Feature 42,0.143775,0.247952,0.0,1.0,2.140417,3.837968,3834
Feature 43,0.499619,0.265275,0.0,1.0,0.078936,-0.572723,77
Feature 44,0.399766,0.247778,0.0,1.0,0.615362,-0.228795,5365
Feature 45,0.000024,0.004870,0.0,1.0,205.316828,42153.000024,2

In [16]:
calculate_statistics(X_real_mslr, n_features_mslr)

,Mean,Std,Min,Max,Skewness,Kurtosis,Unique Values
Feature 0,1.864402,1.254088e+00,0.0,75.0,1.823358,58.479480,20
Feature 1,0.202911,5.679478e-01,0.0,8.0,3.202196,11.259454,9
Feature 2,1.157727,1.018416e+00,0.0,15.0,0.717663,0.550801,14
Feature 3,0.549610,7.835761e-01,0.0,15.0,1.560441,3.170555,13
Feature 4,1.911727,1.220518e+00,0.0,75.0,1.981500,65.093194,20
...,...,...,...,...,...,...,...
Feature 131,17.768581,3.067049e+01,0.0,255.0,3.485848,15.114151,256
Feature 132,24.353330,4.126946e+01,0.0,254.0,2.646238,6.863756,255
Feature 133,223.594063,2.833825e+04,0.0,13150188.0,361.694427,153547.000903,7522
Feature 134,454.567736,1.837117e+04,0.0,2789632.0,73.114535,6659.224679,4125
Feature 135,15554.732763,3.189820e+06,0.0,980000001.0,218.554536,50350.742591,141089